export const themeClasses = {
    slate: {
        header: 'from-slate-500 to-slate-700',
        accentBg: 'bg-slate-500',
        accentText: 'text-slate-500',
        border: 'border-slate-500',
        chipActive: 'bg-slate-500 text-white shadow-md',
        groupActive: 'bg-slate-500 text-white',
    },
    gray: {
        header: 'from-gray-500 to-gray-700',
        accentBg: 'bg-gray-500',
        accentText: 'text-gray-500',
        border: 'border-gray-500',
        chipActive: 'bg-gray-500 text-white shadow-md',
        groupActive: 'bg-gray-500 text-white',
    },
    zinc: {
        header: 'from-zinc-500 to-zinc-700',
        accentBg: 'bg-zinc-500',
        accentText: 'text-zinc-500',
        border: 'border-zinc-500',
        chipActive: 'bg-zinc-500 text-white shadow-md',
        groupActive: 'bg-zinc-500 text-white',
    },
    neutral: {
        header: 'from-neutral-500 to-neutral-700',
        accentBg: 'bg-neutral-500',
        accentText: 'text-neutral-500',
        border: 'border-neutral-500',
        chipActive: 'bg-neutral-500 text-white shadow-md',
        groupActive: 'bg-neutral-500 text-white',
    },
    stone: {
        header: 'from-stone-500 to-stone-700',
        accentBg: 'bg-stone-500',
        accentText: 'text-stone-500',
        border: 'border-stone-500',
        chipActive: 'bg-stone-500 text-white shadow-md',
        groupActive: 'bg-stone-500 text-white',
    },
    red: {
        header: 'from-red-500 to-rose-600',
        accentBg: 'bg-red-500',
        accentText: 'text-red-500',
        border: 'border-red-500',
        chipActive: 'bg-red-500 text-white shadow-md',
        groupActive: 'bg-red-500 text-white',
    },
    orange: {
        header: 'from-orange-500 to-amber-600',
        accentBg: 'bg-orange-500',
        accentText: 'text-orange-500',
        border: 'border-orange-500',
        chipActive: 'bg-orange-500 text-white shadow-md',
        groupActive: 'bg-orange-500 text-white',
    },
    amber: {
        header: 'from-amber-500 to-orange-600',
        accentBg: 'bg-amber-500',
        accentText: 'text-amber-500',
        border: 'border-amber-500',
        chipActive: 'bg-amber-500 text-white shadow-md',
        groupActive: 'bg-amber-500 text-white',
    },
    yellow: {
        header: 'from-yellow-400 to-amber-500',
        accentBg: 'bg-yellow-500',
        accentText: 'text-yellow-500',
        border: 'border-yellow-500',
        chipActive: 'bg-yellow-500 text-white shadow-md',
        groupActive: 'bg-yellow-500 text-white',
    },
    lime: {
        header: 'from-lime-500 to-green-600',
        accentBg: 'bg-lime-500',
        accentText: 'text-lime-500',
        border: 'border-lime-500',
        chipActive: 'bg-lime-500 text-white shadow-md',
        groupActive: 'bg-lime-500 text-white',
    },
    green: {
        header: 'from-green-500 to-emerald-600',
        accentBg: 'bg-green-500',
        accentText: 'text-green-500',
        border: 'border-green-500',
        chipActive: 'bg-green-500 text-white shadow-md',
        groupActive: 'bg-green-500 text-white',
    },
    emerald: {
        header: 'from-emerald-500 to-teal-600',
        accentBg: 'bg-emerald-500',
        accentText: 'text-emerald-500',
        border: 'border-emerald-500',
        chipActive: 'bg-emerald-500 text-white shadow-md',
        groupActive: 'bg-emerald-500 text-white',
    },
    teal: {
        header: 'from-teal-500 to-cyan-600',
        accentBg: 'bg-teal-500',
        accentText: 'text-teal-500',
        border: 'border-teal-500',
        chipActive: 'bg-teal-500 text-white shadow-md',
        groupActive: 'bg-teal-500 text-white',
    },
    cyan: {
        header: 'from-cyan-500 to-sky-600',
        accentBg: 'bg-cyan-500',
        accentText: 'text-cyan-500',
        border: 'border-cyan-500',
        chipActive: 'bg-cyan-500 text-white shadow-md',
        groupActive: 'bg-cyan-500 text-white',
    },
    sky: {
        header: 'from-sky-500 to-blue-600',
        accentBg: 'bg-sky-500',
        accentText: 'text-sky-500',
        border: 'border-sky-500',
        chipActive: 'bg-sky-500 text-white shadow-md',
        groupActive: 'bg-sky-500 text-white',
    },
    blue: {
        header: 'from-blue-500 to-indigo-600',
        accentBg: 'bg-blue-500',
        accentText: 'text-blue-500',
        border: 'border-blue-500',
        chipActive: 'bg-blue-500 text-white shadow-md',
        groupActive: 'bg-blue-500 text-white',
    },
    indigo: {
        header: 'from-indigo-500 to-violet-600',
        accentBg: 'bg-indigo-500',
        accentText: 'text-indigo-500',
        border: 'border-indigo-500',
        chipActive: 'bg-indigo-500 text-white shadow-md',
        groupActive: 'bg-indigo-500 text-white',
    },
    violet: {
        header: 'from-violet-500 to-purple-600',
        accentBg: 'bg-violet-500',
        accentText: 'text-violet-500',
        border: 'border-violet-500',
        chipActive: 'bg-violet-500 text-white shadow-md',
        groupActive: 'bg-violet-500 text-white',
    },
    purple: {
        header: 'from-purple-500 to-fuchsia-600',
        accentBg: 'bg-purple-500',
        accentText: 'text-purple-500',
        border: 'border-purple-500',
        chipActive: 'bg-purple-500 text-white shadow-md',
        groupActive: 'bg-purple-500 text-white',
    },
    fuchsia: {
        header: 'from-fuchsia-500 to-pink-600',
        accentBg: 'bg-fuchsia-500',
        accentText: 'text-fuchsia-500',
        border: 'border-fuchsia-500',
        chipActive: 'bg-fuchsia-500 text-white shadow-md',
        groupActive: 'bg-fuchsia-500 text-white',
    },
    pink: {
        header: 'from-pink-500 to-rose-600',
        accentBg: 'bg-pink-500',
        accentText: 'text-pink-500',
        border: 'border-pink-500',
        chipActive: 'bg-pink-500 text-white shadow-md',
        groupActive: 'bg-pink-500 text-white',
    },
    rose: {
        header: 'from-rose-500 to-pink-600',
        accentBg: 'bg-rose-500',
        accentText: 'text-rose-500',
        border: 'border-rose-500',
        chipActive: 'bg-rose-500 text-white shadow-md',
        groupActive: 'bg-rose-500 text-white',
    },
} as const;
